# Header
menu:
  Home: /
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- profile
- category
- tag
- tagcloud
- recent_posts
- archive
- ads

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics: UA-108646205-1
gauges_analytics:
favicon: /favicon.png
twitter: '@azriton'
google_plus:
fb_admins:
fb_app_id:
